#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

# shellcheck source=themes/dracula.sh
source "$SCRIPT_DIR/dracula.sh"

# ── Polybar ────────────────────────────────────────────────────────────────
cat > "$REPO_DIR/config/polybar/colors.ini" << EOF
[dracula]
background = $BACKGROUND
current    = $CURRENT
foreground = $FOREGROUND
comment    = $COMMENT
cyan       = $CYAN
green      = $GREEN
orange     = $ORANGE
pink       = $PINK
purple     = $PURPLE
red        = $RED
yellow     = $YELLOW
EOF
echo "  generated: config/polybar/colors.ini"

# ── i3 ────────────────────────────────────────────────────────────────────
cat > "$REPO_DIR/config/i3/colors.conf" << EOF
# Dracula color palette — generated by themes/generate.sh
set \$dracula_bg      $BACKGROUND
set \$dracula_cur     $CURRENT
set \$dracula_fg      $FOREGROUND
set \$dracula_cmt     $COMMENT
set \$dracula_cya     $CYAN
set \$dracula_grn     $GREEN
set \$dracula_ora     $ORANGE
set \$dracula_pnk     $PINK
set \$dracula_pur     $PURPLE
set \$dracula_red     $RED
set \$dracula_yel     $YELLOW
EOF
echo "  generated: config/i3/colors.conf"

# ── Starship ──────────────────────────────────────────────────────────────
STARSHIP="$REPO_DIR/config/starship/starship.toml"
PALETTE_BLOCK="[palettes.dracula]
background = \"$BACKGROUND\"
current    = \"$CURRENT\"
foreground = \"$FOREGROUND\"
comment    = \"$COMMENT\"
cyan       = \"$CYAN\"
green      = \"$GREEN\"
orange     = \"$ORANGE\"
pink       = \"$PINK\"
purple     = \"$PURPLE\"
red        = \"$RED\"
yellow     = \"$YELLOW\""

# Replace [palettes.dracula] section in-place:
# skip key=value lines immediately following the section header,
# then inject the new block.
awk -v block="$PALETTE_BLOCK" '
  /^\[palettes\.dracula\]/ { print block; skip=1; next }
  skip && /^[[:alpha:]]/ { next }
  { skip=0; print }
' "$STARSHIP" > "$STARSHIP.tmp" && mv "$STARSHIP.tmp" "$STARSHIP"
echo "  updated:   config/starship/starship.toml"

echo "Done."
